---
output: word_document
---

```{r echo=F, results="hide"}
library(pacman)
p_load(knitr)
p_load(rmarkdown)
p_load(pander)
#opts_chunk$set(dpi=75)
```


```{r echo=F,warning=F,error=F,message=F}
source("combine.R")
data <-  latestData() 
mostRecentData <- data %>%
    select(country,year,NUTS.Code,NUTS3.name,ha) %>%
    arrange(NUTS.Code)

pander(mostRecentData,digits=1,caption="Citrus product surface area per NUTS3 region")
```

```{r echo=F,warning=F,error=F,message=F}
countryHa <- data %>%
    group_by(country) %>% summarise(sum(ha))

pander(countryHa,digits=0,caption="Citrus product surface area per country")
```

```{r echo=F,warning=F,error=F,message=F}
comments <- data %>%
    mutate(comment=ifelse(is.na(comment),"",comment)) %>%
    group_by(country,year,comment) %>%
    select(country,comment) %>%
    slice(1)
pander(comments,caption="Notes on potential data transformations")
```


```{r fig.height=14/2.4, fig.width=14,dpi=600,echo=T,warning=F,message=F}
base_layer() +
worldCountries_layer(world.eu) +
    citrusSurface_layer(alpha=1) +
    nuts3_layer() +
    nuts0_layer() +
    tm_format_Europe()
```

```{r fig.height=14/2.4, fig.width=14,dpi=600,echo=T,warning=F,message=F}
base_layer() +
worldCountries_layer(world.eu) +
    citrusSurface_layer(alpha=1) +
    nuts3_layer() +
    nuts0_layer() +
    tm_format_Europe()
```
